name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/andstep228/osis-workspace-dec6:1.0 .
      - run: docker push ghcr.io/andstep228/osis-workspace-dec6:1.0
      - run: docker build -t ghcr.io/andstep228/osis-ex-python-node/node-app:1.0 ./node-app
      - run: docker push ghcr.io/andstep228/osis-ex-python-node/node-app:1.0
      - run: ssh  -o "StrictHostKeyChecking no" 'andstep228-78odejdu-axe7h6pk2yt#glFDJ2f7KdbS21AlmbKvAnF0kQ0_Y5Kf@andstep228-78odejdu-axe7h6pk2yt.ssh.ws-eu106.gitpod.io' "cd /workspace/7-8Odejdu/osis-python-auto && docker compose pull && docker compose up -d"

      
